//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnibrewREST
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTmoment
    {
        public int Id { get; set; }
        public Nullable<double> bottle01 { get; set; }
        public Nullable<double> bottle02 { get; set; }
        public Nullable<double> bottle03 { get; set; }
        public Nullable<double> bottle04 { get; set; }
        public Nullable<double> bottle05 { get; set; }
        public Nullable<double> bottle06 { get; set; }
        public Nullable<double> bottle07 { get; set; }
        public Nullable<double> bottle08 { get; set; }
        public Nullable<double> bottle09 { get; set; }
        public Nullable<double> bottle10 { get; set; }
        public Nullable<double> bottle11 { get; set; }
        public Nullable<double> bottle12 { get; set; }
        public Nullable<double> bottle13 { get; set; }
        public Nullable<double> bottle14 { get; set; }
        public Nullable<double> bottle15 { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
    }
}
